### ISSUE TITLE
Issue in add_annotation

### ISSUE THREAD

**Issue by bertoky** [dopefishh/pympi#1]
Hi, I get the next error when I use the method add_annotation:

ValueError: Tier already contains ref annotations...

But only when I work with tiers with ref annotations, is it not possible use this method with this kind of tiers or I have to write something else in the parameter svg_ref?

Thank  you so much.

**Comment by dopefishh** [comment]
If a tier contains reference annotations you can't add normal annotations and vice versa. You should use [this](http://dopefishh.github.io/pympi/Elan.html#pympi.Elan.Eaf.add_ref_annotation) then instead.
This is a constraint of the EAF file format.
Let me know if this solves the problem or if you have any other questions. Thanks for the feedback!

**Comment by bertoky** [comment]
Yes, I have understood, but when I work with your EAF example file (sample_2.8.eaf) when I'm trying to add a normal annotation, for instance:

eaf = pympi.Elan.Eaf('sample_2.8.eaf')
eaf.add_annotation ('gestures', 3090, 4070, '123456')

The file don't change, I have to do anything else?

Thank you so much

**Comment by dopefishh** [comment]
After you make changes you have to write it to file with the [to_file function](http://dopefishh.github.io/pympi/Elan.html#pympi.Elan.Eaf.to_file)

**Comment by dopefishh** [comment]
You could check [this](https://github.com/dopefishh/pympi/tree/master/examples) for some examples. Note that they are written for somewhat older versions.
