### ISSUE TITLE
XML Namespace problem when opening and saving a file

### ISSUE THREAD

**Issue by thomaskisler** [dopefishh/pympi#15]
When opening and saving an EAF file with pympi, the resulting XML file fails to validate due to namespace information being added twice to the output file.

An MWE is:

`import pympi`
`filename = "minimalExample.eaf"`
`eafObj = pympi.Elan.Eaf(filename)`
`eafObj.to_file(filename)`

A very easy and short eaf file with which the error can be reproduced is attached (needed to replace the extension from eaf to txt to to upload it): [minimalExample.txt](https://github.com/dopefishh/pympi/files/3110970/minimalExample.txt)

**Comment by dopefishh** [comment]
Thanks for reporting. I'll try to find time this week

**Comment by dopefishh** [comment]
Dear thomaskisler.
I cannot reproduce this.

I did the following:

```
$ git clone github.com:dopefishh/pympi
$ cd pympi
$ virtualenv -p python2 env
$ . env/bin/activate
$ python setup.py install
$ wget -O minimal.eaf https://github.com/dopefishh/pympi/files/3110970/minimalExample.txt
$ python 
Python 2.7.16 (default, Apr  6 2019, 01:42:57)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pympi
>>> eafObj = pympi.Elan.Eaf("minimal.eaf")
Parsing unknown version of ELAN spec... This could result in errors...
>>> eafObj.to_file("minimal2.eaf")
$ diff minimal.eaf minimal2.eaf
```

There is no difference in files and they both open fine in ELAN

**Comment by thomaskisler** [comment]
You are right, I can neither. If I ever find a way, I reopen this issue.
