### ISSUE TITLE
Extraction function is bugged

### ISSUE THREAD

**Issue by hadware** [dopefishh/pympi#17]
The `Eaf.extract` function has a bug that renders it completely useless:

Line 478 of the` elan.py` file should be 
```python3
eaf_out.remove_annotation(t, (ae - ab)//2, False)
```

Correct me if i'm mistaken, I'll pull-request a fix if you wish and if it makes sense to you.

**Comment by dopefishh** [comment]
I think you are right. You are very welcome to make a pull request.

**Comment by hadware** [comment]
Very well, I'll take care of it ASAP.
