### ISSUE TITLE
copy tier within the same file

### ISSUE THREAD

**Issue by Cogitarian** [dopefishh/pympi#24]
**Expected behaviour**
I need to copy (duplicate) tier in one file or from one file to another and I don't understand the syntax: how copy function is supposed to work? 

**Actual behaviour**
I'd like to copy tier and change its name within one file. Next, I'd like to loop it over tens of other ear files. I thought copy_tier would work, but it doesn't. I've tried to copy tier from one object to another, but then got errors (see [screenshot](https://drive.google.com/open?id=1bWTOoFoDMq_qHUgV39g9CuhBlLp19cvx)).

**System information**
- python version: 
- os:
- are you up to date with the latest master?:  

**Additional context**

**Comment by dopefishh** [comment]
I cannot open your screenshot, can you copy paste the errors in the issue?

**Comment by Cogitarian** [comment]
Sure, I'd happy to:

eafexp1.copy_tier(eafexp1,"lh_Activation_R2")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/cogitarian/PycharmProjects/PYMPI/venv/lib/python3.7/site-packages/pympi/Elan.py", line 432, in copy_tier
    tier_dict=self.get_parameters_for_tier(tier_name))
  File "/Users/cogitarian/PycharmProjects/PYMPI/venv/lib/python3.7/site-packages/pympi/Elan.py", line 871, in get_parameters_for_tier
    return self.tiers[id_tier][2]
KeyError: 'lh_Activation_R2'
eafexp.copy_tier(eafexp1,"lh_Activation_R2")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/cogitarian/PycharmProjects/PYMPI/venv/lib/python3.7/site-packages/pympi/Elan.py", line 432, in copy_tier
    tier_dict=self.get_parameters_for_tier(tier_name))
  File "/Users/cogitarian/PycharmProjects/PYMPI/venv/lib/python3.7/site-packages/pympi/Elan.py", line 871, in get_parameters_for_tier
    return self.tiers[id_tier][2]
KeyError: 'lh_Activation_R2'
eafexp.copy_tier(eafexp,"lh_Activation_R2")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/cogitarian/PycharmProjects/PYMPI/venv/lib/python3.7/site-packages/pympi/Elan.py", line 432, in copy_tier
    tier_dict=self.get_parameters_for_tier(tier_name))
  File "/Users/cogitarian/PycharmProjects/PYMPI/venv/lib/python3.7/site-packages/pympi/Elan.py", line 871, in get_parameters_for_tier
    return self.tiers[id_tier][2]

**Comment by dopefishh** [comment]
Are you sure there is a tier with that exact name in the original object? Can you maybe attach the elan file and the script as well.

**Comment by Cogitarian** [comment]
Right, it works between different files, but not within one file, perhaps because elan does not accept two tiers with the same name. I guess the solution would be to copy the tier a temporary file and after changing its name copy it again into original file. I'll try that later. Any other solutions?

**Comment by Cogitarian** [comment]
OK, here is new function to duplicate tiers within the same eaf file. Unfortunately the result is a tier with duplicated annotations and I have no idea why this happens, as you can't do that in elan manually. I'm sure there is a bug in my function or there is room for improvement. Any ideas? 

Here are two files: [temporary.eaf](https://drive.google.com/open?id=16zY1_UFDKlqmKVeiUA6qgmehv17fDLss) is a file with just one empty tier and it is used to make a temporary copy of a tier from the [annotated.eaf](https://drive.google.com/open?id=1F3EPAcbB7lgSikoAvqKR_mQCxfo-j3lp). [The new file is here](https://drive.google.com/open?id=1G-NhO5jnfws1YNXDDb0EwfyWTM4igbUU). I hope you can run the code to reproduce the bug seen on this [screenshot](https://drive.google.com/open?id=1CgiXqOMQtGURBmGdO_Fu3QVBdZV6qkPG).

**Comment by Cogitarian** [comment]
OK, I've solved it with another elan object. The [function](https://drive.google.com/open?id=1mleqHeWneajS9T4wmGyUEyVxGNsAd_hJ) doesn't look pretty but it works for me.

**Comment by dopefishh** [comment]
Good to hear that the problem is solved. Small note, initializing an EAF object without filename is fine as well. This will just create an empty EAF file.

**Comment by hoikiki** [comment]
> OK, here is new [function](https://drive.google.com/open?id=1soJtagJSh13WYv4dWGWP_FpMxotgwoco) to duplicate tiers within the same eaf file. Unfortunately the result is a tier with duplicated annotations and I have no idea why this happens, as you can't do that in elan manually. I'm sure there is a bug in my function or there is room for improvement. Any ideas?
> 
> Here are two files: [temporary.eaf](https://drive.google.com/open?id=16zY1_UFDKlqmKVeiUA6qgmehv17fDLss) is a file with just one empty tier and it is used to make a temporary copy of a tier from the [annotated.eaf](https://drive.google.com/open?id=1F3EPAcbB7lgSikoAvqKR_mQCxfo-j3lp). [The new file is here](https://drive.google.com/open?id=1G-NhO5jnfws1YNXDDb0EwfyWTM4igbUU). I hope you can run the code to reproduce the bug seen on this [screenshot](https://drive.google.com/open?id=1CgiXqOMQtGURBmGdO_Fu3QVBdZV6qkPG).

**Comment by hoikiki** [comment]
> OK, here is new [function](https://drive.google.com/open?id=1soJtagJSh13WYv4dWGWP_FpMxotgwoco) to duplicate tiers within the same eaf file. Unfortunately the result is a tier with duplicated annotations and I have no idea why this happens, as you can't do that in elan manually. I'm sure there is a bug in my function or there is room for improvement. Any ideas?
> 
> Here are two files: [temporary.eaf](https://drive.google.com/open?id=16zY1_UFDKlqmKVeiUA6qgmehv17fDLss) is a file with just one empty tier and it is used to make a temporary copy of a tier from the [annotated.eaf](https://drive.google.com/open?id=1F3EPAcbB7lgSikoAvqKR_mQCxfo-j3lp). [The new file is here](https://drive.google.com/open?id=1G-NhO5jnfws1YNXDDb0EwfyWTM4igbUU). I hope you can run the code to reproduce the bug seen on this [screenshot](https://drive.google.com/open?id=1CgiXqOMQtGURBmGdO_Fu3QVBdZV6qkPG).

The URL was not found. I get stuck with duplicate tiers within the same eaf file. Thank you!
