### ISSUE TITLE
EAF 3.0 file format support

### ISSUE THREAD

**Issue by dopefishh** [dopefishh/pympi#29]
Currently only 2.7 and 2.8 are officially _supported_ and a warning is given when another version is imported.

The scheme is available here: http://www.mpi.nl/tools/elan/EAFv3.0.xsd

A human readable explanation is available here:
https://www.mpi.nl/tools/elan/EAF_Annotation_Format_3.0_and_ELAN.pdf

It should be added to the _supported_ list after checking and implementing the differences in spec.

**Comment by xrotwang** [comment]
I don't know much about the EAF format. But the changelog in the schema sounds like not too much has changed:

> VERSION 3.0
>	DATE December 2016
>	- added two referential link elements, CROSS_REF_LINK and GROUP_REF_LINK, contained in 
>	sets of such elements, REF_LINK_SET.

**Comment by dopefishh** [comment]
Those advanced reference options weren't supported previously either so we can safely parse 3.0 I guess.
