### ISSUE TITLE
Remove ref annotations

### ISSUE THREAD

**Issue by bertoky** [dopefishh/pympi#3]
Hi again,

I'm trying remove some reference annotations with the methods remove_annotation() or clean_time_slots()  but they have no effect. When I tried with time annotations it worked properly... Is anything that I could do?

Thank you so much, I should send you a couple of beers more ;)

**Comment by dopefishh** [comment]
I'll work on this

**Comment by bertoky** [comment]
Great, thank you so much!

**Comment by dopefishh** [comment]
It should be fixed now. See the [changelog](http://dopefishh.github.io/pympi/index.html) for version 1.59. Let me know if there are still problems!
