### ISSUE TITLE
Order in method get_ref_annotation_data_for_tier()

### ISSUE THREAD

**Issue by bertoky** [dopefishh/pympi#4]
Hi again,

when I use the method get_annotation_data_for_tier() I get the information in the same order that it is in the eaf file whereas when I use the method get_ref_annotation_data_for_tier() I don't get the information in the same order that it is in the eaf file so how is the order of getting this information?

Thank you so much again.

**Comment by dopefishh** [comment]
Because the data is stored in a dictionary the data is inherently unordered. Because of the structure of the returned data you can easily sort the data. Either in place using the `your_list.sort()` function of make a new list from it by wrapping in in `sorted(your_list)`.
