### ISSUE TITLE
Release version 1.7 has a lower version number than the previous release (1.69)

### ISSUE THREAD

**Issue by gedankenexperimenter** [dopefishh/pympi#40]
When specifying a dependency on `pympi-ling` in a `setup.cfg` file for a python package, if include the following:
```
install_requires =
    pympi-ling>=1.69
```
…and version 1.7 is already installed, it will be removed in favour of 1.69 when installing the dependent package with `pip`. Alternatively, with this:
```
install_requires =
    pympi-ling>=1.7
```
…version 1.69 will satisfy that dependency, and will not be replaced with version 1.7.

The correct [semantic version number](https://semver.org) should be 1.70, not 1.7.

**Comment by dopefishh** [comment]
thank you

**Comment by gedankenexperimenter** [comment]
Would you mind publishing 1.70 to PyPI? It would be really nice to not get the warnings about version 3.0 of EAF files when running tests.

**Comment by dopefishh** [comment]
Yes, there is one blocking issue still. If that's fixed the new version will be pushed. I'll try to allocate some time this week for that.

**Comment by gedankenexperimenter** [comment]
The main issue I had was that call to `warnings.warn()` in Elan.py, which was printing a message to STDOUT instead of STDERR. I've worked out how to use `contextlib.redirect_stdout()` to fix that, so my use case is not urgent.
