### ISSUE TITLE
Parsing unknown version of ELAN spec

### ISSUE THREAD

**Issue by mesadhan** [dopefishh/pympi#43]
**Sample Code Script**

```py
import pympi
path_to_eaf = "4001.eaf"
EAF = pympi.Elan.Eaf(file_path=path_to_eaf, author='pympi')
```
**Output**
> Parsing unknown version of ELAN spec... This could result in errors...

**System information**
- python version:  3.9.0
- os: Windows 10
- are you up to date with the latest master?:  Yes

**Additional context**
I'm using Elan v6.1 to produce the `*.eaf` file.

**Comment by dopefishh** [comment]
It seems that there is a new version of the EAF file specification. You can suppress the warning by changing the third line to:

```
EAF = pympi.Elan.Eaf(file_path=path_to_eaf, author='pympi', suppress_version_warning=False)
```

I have to look into the new specification to see if something changed.
