### ISSUE TITLE
Can you please update the version for pip install? 

### ISSUE THREAD

**Issue by benfoley** [dopefishh/pympi#44]
**Expected behaviour**
I love working with this package, and expected that pip install would install the most recent version, especially the Elan version error message suppression fix.

**Actual behaviour**
Installing with pip installs an old version.

**System information**
- python version: 3
- os: osx 
- are you up to date with the latest master?:  n/a

**Comment by dopefishh** [comment]
There are several open issues I would like to close before uploading a new version. Nonetheless, the current package is quite outdated so I'll upload a new version next week

**Comment by dopefishh** [comment]
I've, after wrestling with pypi, uploaded a new version:
https://pypi.org/project/pympi-ling/
