### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'README.rst' when installing from pip

### ISSUE THREAD

**Issue by cl-s** [dopefishh/pympi#5]
Hi there,

I seem to be having issues installing the latest version (v1.59) using pip.

The log output is as follows:

    $ pip install pympi-ling
    Collecting pympi-ling
      Using cached pympi-ling-1.59.tar.gz
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "/tmp/pip-build-pA3iNI/pympi-ling/setup.py", line 13, in <module>
            long_description=open('README.rst').read(),
        IOError: [Errno 2] No such file or directory: 'README.rst'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
        
          File "<string>", line 20, in <module>
        
          File "/tmp/pip-build-pA3iNI/pympi-ling/setup.py", line 13, in <module>
        
            long_description=open('README.rst').read(),
        
        IOError: [Errno 2] No such file or directory: 'README.rst'
        
        ----------------------------------------
        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pA3iNI/pympi-ling

This issue doesn't seem to affect the install when doing a manual install from the repository. 

However, I notice in the tarball hosted on PyPI the file `README.rst` is missing from the package's root directory so when setup.py tries to read it in it can't be found.

**Comment by j6k4m8** [comment]
Replacing that line with `long_description='a project without a readme',` does nicely... Looks like the pypi tarball is borken!

**Comment by dopefishh** [comment]
Sorry accidentally pressed close. For some unknown reason the `README.rst` didn't appear in the tarball. I will fix this asap

**Comment by dopefishh** [comment]
Meh, I messed it up, my fancy RST readme is gone from the long description:( This will take some extra time...

**Comment by dopefishh** [comment]
Okay it seems to work now. `pip install pympi-ling==1.59c`

**Comment by cl-s** [comment]
Great thanks @dopefishh! That seems to work for me now too.

**Comment by mehaksharma1993** [comment]
How to fix this problem?

**Comment by dopefishh** [comment]
Aw, that's a pity. That bug slipped through while uploading. You can still
install the package by hand. I will fix this as soon as possible.

Thanks for the feedback, if you have any other questions or feedback please let
me know.

Best,
Mart

**Comment by dopefishh** [comment]
Dear mehaksharma1993

The latest release should fix this.

Best,
Mart
