### ISSUE TITLE
Problem saving EAF files

### ISSUE THREAD

**Issue by bertoky** [dopefishh/pympi#6]
Hi again,

I have found a problem, when I do simply:

eaf = pympi.Elan.Eaf(input_file)

eaf.to_file (output_file)

input_file and output_file have not the same order in the tiers, what can I do?

Thank you so much again.

**Comment by dopefishh** [comment]
Thanks for the feedback, [version 1.6](https://pypi.python.org/pypi/pympi-ling/1.6) should fix this.

Best,
Mart
